### ISSUE TITLE
[Feature Request] Example Of MMM using known parameters

### ISSUE THREAD

**Issue by alexhallam** [DoktorMike/dammmdatagen#2]
Would it be possible, maybe in a future vignette, to have an example of generating MMM data with known parameters then recover those parameters via modeling?

**Comment by DoktorMike** [comment]
That is definitely doable. Will look into it. I'm a bit slammed at the moment.

**Comment by DoktorMike** [comment]
So a little more than 3 years later I made an example function with parameters which generates a KPI. This function is called `generateRetailData` but it doesn't allow the user to specify the regression coefficients but rather decides them itself. It returns the 

- Covariates
- Effects
- Response

I'll try to make a small vignette about this too. Closing this for now. Please reopen if it doesn't solve your issue.
