### ISSUE TITLE
generateData() arguments

### ISSUE THREAD

**Issue by rebeccayiunyc** [DoktorMike/dammmdatagen#3]
Thanks for sharing this package!! It's tremendously helpful. 
Some of the arguments in generateData() function don't seem to be working tho. E.g. function is not responding to kpi, onlineInsertionNames, etc. 
Any idea how to fix this?

**Comment by DoktorMike** [comment]
This has been addressed in the `generateRetailData` function @rebeccayiunyc 

Please have a look if still relevant. Closing here for now.
